// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzifpsemodfgssebrgxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6aWZwc2Vtb2RmZ3NzZWJyZ3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDY3MDEsImV4cCI6MjA2MDMyMjcwMX0.fvmWbzh7qpDVUYuO7cqOM6W2V8A6Bb3M7MujoTFSpbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);